// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv25AWlidVecd688hV03mlloBJgFU1z0c',
    appId: '1:226874861188:web:b76d143771ece7acae04d1',
    messagingSenderId: '226874861188',
    projectId: 'midtest-924d5',
    authDomain: 'midtest-924d5.firebaseapp.com',
    storageBucket: 'midtest-924d5.appspot.com',
    measurementId: 'G-1JVD6TFSML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4BglPfI_sqTXNmyb6Zi-v7KLD8IcXtNs',
    appId: '1:226874861188:android:a6431f9dd42e2002ae04d1',
    messagingSenderId: '226874861188',
    projectId: 'midtest-924d5',
    storageBucket: 'midtest-924d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2q1zdXNp_a8yeu1c_4nUyWx1bVVticb8',
    appId: '1:226874861188:ios:c77a248a3434be23ae04d1',
    messagingSenderId: '226874861188',
    projectId: 'midtest-924d5',
    storageBucket: 'midtest-924d5.appspot.com',
    iosBundleId: 'com.example.midtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2q1zdXNp_a8yeu1c_4nUyWx1bVVticb8',
    appId: '1:226874861188:ios:c77a248a3434be23ae04d1',
    messagingSenderId: '226874861188',
    projectId: 'midtest-924d5',
    storageBucket: 'midtest-924d5.appspot.com',
    iosBundleId: 'com.example.midtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv25AWlidVecd688hV03mlloBJgFU1z0c',
    appId: '1:226874861188:web:d02752bf00e6e2cbae04d1',
    messagingSenderId: '226874861188',
    projectId: 'midtest-924d5',
    authDomain: 'midtest-924d5.firebaseapp.com',
    storageBucket: 'midtest-924d5.appspot.com',
    measurementId: 'G-8ZGN1FR00R',
  );
}
